---
# Make everything really small
#
# large  => medium
# medium => small
# small  => nano

- type: replace
  path: /instance_groups/name=api/vm_type
  value: medium

- type: replace
  path: /instance_groups/name=cc-worker/vm_type
  value: small

- type: replace
  path: /instance_groups/name=diego-api/vm_type
  value: small

- type: replace
  path: /instance_groups/name=doppler/vm_type
  value: high_cpu_xlarge

- type: replace
  path: /instance_groups/name=log-api/vm_type
  value: high_cpu_xlarge

- type: replace
  path: /instance_groups/name=nats/vm_type
  value: small

- type: replace
  path: /instance_groups/name=scheduler/vm_type
  value: small

- type: replace
  path: /instance_groups/name=uaa/vm_type
  value: small

- type: replace
  path: /instance_groups/name=router/vm_type
  value: slim_router

- type: replace
  path: /instance_groups/name=prometheus/vm_type
  value: small
